# Generated by Django 6.0.6 on 2026-06-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'experience'},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='is_project',
        ),
    ]
